<?php

class FunctionCommon {

    public static $registroDeDatos = array(
        '1' => 'Realizaste los registros de datos con éxito.',
        '2' => 'Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente.',
        '3' => 'Registrar los datos es importante para implementar tus estrategias. Recordá realizarlo cuidadosamente. '
    );
    public static $procesamientoDeDatos = array(
        '1' => 'Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia.',
        '2' => 'Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente.',
        '3' => 'Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia. ',
    );

    public static function convert_date_from_db_for_view($date,$format=NULL) {
        if (!is_string($date) || trim($date) == "") {
            return "";
        }
        $temp = explode(" ", $date);
        $temp = $temp[0];
        $temp = explode("-", $temp);
        if($format==NULL){
            $format=DATE_FORMAT_FOR_VIEW;
        }        
        if($format=="d-m-y"){
            return $temp[2] . '/' . $temp[1] . '/' . $temp[0];
        }
        else if($format=="y-m-d"){
            return $temp[0] . '/' . $temp[1] . '/' . $temp[1];
        }
        return "";
    }
    public static function convert_date_for_saving_db($date,$format=NULL) {
        if (!is_string($date) || trim($date) == "") {
            return "0000-00-00 00:00:00";
        }        
        $temp = explode("/", $date);
        if($format==NULL){
            $format=DATE_FORMAT_FOR_VIEW;
        }        
        if($format=="d-m-y"){
            return $temp[2] . '-' . $temp[1] . '-' . $temp[0]. ' 01:01:01';
        }
        else if($format=="y-m-d"){
            return $temp[0] . '-' . $temp[1] . '-' . $temp[1]. ' 01:01:01';
        }
        return "0000-00-00 00:00:00";
    }

    public static function test() {
        debug("123");
    }

    /*
      average cost per day
     */

    public static function avg_day($total_cost, $num_date) {
        if ($num_date) {
            $result = $total_cost / $num_date;
            return $result;
        }
        return '';
    }

    /*
      average cost per day of a person
     */

    public static function avg_day_person($total_cost, $num_date, $number_member) {
        if ($num_date && $number_member) {
            $result = ($total_cost / $num_date) / $number_member;
            return $result;
        }

        return '';
    }

    /*
      differene cost in a day
     */

    public static function dif_day($before, $after) {
        return $after - $before;
    }

    public static function evalue_management($before, $after, $plan, $compare_result, $result) {
        $no = $before * 10000 + $after * 1000 + $plan * 100 + $compare_result * 10 + $result;
        $expressions = array(
            '3333' => 'Lograste analizar la situación de tu hogar. Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Aplicaste con éxito tus estrategias. Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Trabajaste de manera eficiente e incorporaste nuevos hábitos.',
            '33331' => 'Lograste analizar la situación de tu hogar. Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Aplicaste con éxito tus estrategias. Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos. ',
            '33323' => 'Lograste analizar la situación de tu hogar. Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Aplicaste con éxito tus estrategias.. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente.',
            '33321' => 'Lograste analizar la situación de tu hogar. Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Aplicaste con éxito tus estrategias. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos. ',
            '33313' => 'Lograste analizar la situación de tu hogar. Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Aplicaste con éxito tus estrategias. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia.',
            '33311' => 'Lograste analizar la situación de tu hogar. Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Aplicaste con éxito tus estrategias. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '33233' => 'Lograste analizar la situación de tu hogar. Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente.',
            '33231' => 'Lograste analizar la situación de tu hogar. Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '33223' => 'Lograste analizar la situación de tu hogar. Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente.',
            '33221' => 'Lograste analizar la situación de tu hogar. Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '33213' => 'Lograste analizar la situación de tu hogar. Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia.',
            '33211' => 'Lograste analizar la situación de tu hogar. Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '33133' => 'Lograste analizar la situación de tu hogar. Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente.',
            '33131' => 'Lograste analizar la situación de tu hogar. Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '33123' => 'Lograste analizar la situación de tu hogar. Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente.',
            '33121' => 'Lograste analizar la situación de tu hogar. Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '33113' => 'Lograste analizar la situación de tu hogar. Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia.',
            '33111' => 'Lograste analizar la situación de tu hogar. Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos. ',
            '32333' => 'Lograste analizar la situación de tu hogar. Aplicaste con éxito tus estrategias. Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable.',
            '32331' => 'Lograste analizar la situación de tu hogar. Aplicaste con éxito tus estrategias. Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '32323' => 'Lograste analizar la situación de tu hogar. Aplicaste con éxito tus estrategias. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente.',
            '32321' => 'Lograste analizar la situación de tu hogar. Aplicaste con éxito tus estrategias. Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '32313' => 'Lograste analizar la situación de tu hogar. Aplicaste con éxito tus estrategias. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia.',
            '32311' => 'Lograste analizar la situación de tu hogar. Aplicaste con éxito tus estrategias. Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos. ',
            '32233' => 'Lograste analizar la situación de tu hogar. Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente.',
            '32231' => 'Lograste analizar la situación de tu hogar. Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '32223' => 'Lograste analizar la situación de tu hogar. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente.',
            '32221' => 'Lograste analizar la situación de tu hogar. Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '32213' => 'Lograste analizar la situación de tu hogar.  Trabajaste de maneraeficiente e incorporaste nuevos hábitos.  Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable.  Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente.  Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia.',
            '32211' => 'Lograste analizar la situación de tu hogar.  Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable.  Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente.  Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia.  Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '32133' => 'Lograste analizar la situación de tu hogar.  Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia.  Trabajaste de maneraeficiente e incorporaste nuevos hábitos.  Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable.  Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente.',
            '32131' => 'Lograste analizar la situación de tu hogar.  Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia.  Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable.  Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente.  Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos. ',
            '32123' => 'Lograste analizar la situación de tu hogar.  Trabajaste de maneraeficiente e incorporaste nuevos hábitos.  Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable.  Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente.  Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente. ',
            '32121' => 'Lograste analizar la situación de tu hogar.  Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable.  Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente.  Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente.  Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '32113' => 'Lograste analizar la situación de tu hogar.  Trabajaste de maneraeficiente e incorporaste nuevos hábitos.  Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable.  Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente.  Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia.',
            '32111' => 'Lograste analizar la situación de tu hogar.  Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable.  Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente.  Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia.  Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '31333' => 'Lograste analizar la situación de tu hogar. Aplicaste con éxito tus estrategias. Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable.',
            '31331' => 'Lograste analizar la situación de tu hogar. Aplicaste con éxito tus estrategias. Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '31323' => 'Lograste analizar la situación de tu hogar. Aplicaste con éxito tus estrategias. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente.',
            '31321' => 'Lograste analizar la situación de tu hogar. Aplicaste con éxito tus estrategias. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '31313' => 'Lograste analizar la situación de tu hogar. Aplicaste con éxito tus estrategias. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia.',
            '31311' => 'Lograste analizar la situación de tu hogar. Aplicaste con éxito tus estrategias. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '31233' => 'Lograste analizar la situación de tu hogar. Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente.',
            '31231' => 'Lograste analizar la situación de tu hogar. Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '31223' => 'Lograste analizar la situación de tu hogar. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente.',
            '31221' => 'Lograste analizar la situación de tu hogar. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '31213' => 'Lograste analizar la situación de tu hogar. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia.',
            '31211' => 'Lograste analizar la situación de tu hogar. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '31133' => 'Lograste analizar la situación de tu hogar. Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente.',
            '31131' => 'Lograste analizar la situación de tu hogar. Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos. ',
            '31123' => 'Lograste analizar la situación de tu hogar. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente.',
            '31121' => 'Lograste analizar la situación de tu hogar. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '31113' => 'Lograste analizar la situación de tu hogar. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia.',
            '31111' => 'Lograste analizar la situación de tu hogar. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '13333' => 'Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Aplicaste con éxito tus estrategias. Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar.',
            '13331' => 'Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Aplicaste con éxito tus estrategias. Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '13323' => 'Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Aplicaste con éxito tus estrategias. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente.',
            '13321' => 'Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Aplicaste con éxito tus estrategias. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '13313' => 'Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Aplicaste con éxito tus estrategias. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia.',
            '13311' => 'Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Aplicaste con éxito tus estrategias. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '13233' => 'Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente.',
            '13231' => 'Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '13223' => 'Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente.',
            '13221' => 'Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '13213' => 'Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia.',
            '13211' => 'Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '13133' => 'Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente.',
            '13131' => 'Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '13123' => 'Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente.',
            '13121' => 'Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '13113' => 'Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia.',
            '13111' => 'Planificaste estrategias de forma creativa y orientadas hacia un consumo responsable. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '12333' => 'Aplicaste con éxito tus estrategias. Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable.',
            '12331' => 'Aplicaste con éxito tus estrategias. Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '12323' => 'Aplicaste con éxito tus estrategias. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente.',
            '12321' => 'Aplicaste con éxito tus estrategias. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '12313' => 'Aplicaste con éxito tus estrategias. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia.',
            '12311' => 'Aplicaste con éxito tus estrategias. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '12233' => 'Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente.',
            '12231' => 'Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '12223' => 'Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente.',
            '12221' => 'Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '12213' => 'Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia.',
            '12211' => 'Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '12133' => 'Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable. Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente.',
            '12131' => 'Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable. Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '12123' => 'Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable. Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente.',
            '12121' => 'Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable. Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '12113' => 'Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable. Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia.',
            '12111' => 'Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Planificaste estrategias de forma creativa. Buscá orientarlas hacia un consumo responsable. Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '11333' => 'Aplicaste con éxito tus estrategias. Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable.',
            '11331' => 'Aplicaste con éxito tus estrategias. Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '11323' => 'Aplicaste con éxito tus estrategias. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente.',
            '11321' => 'Aplicaste con éxito tus estrategias. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '11313' => 'Aplicaste con éxito tus estrategias. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia. ',
            '11311' => 'Aplicaste con éxito tus estrategias. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '11233' => 'Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente.',
            '11231' => 'Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '11223' => 'Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente.',
            '11221' => 'Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '11213' => 'Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia.',
            '11211' => 'Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Estuviste realizando los registros necesarios. Recordá siempre que cuando los obtengas tenés que hacerlo cuidadosamente. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '11133' => 'Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente.',
            '11131' => 'Hiciste un excelente trabajo en la comparación de datos antes y durante la puesta en marcha de la estrategia. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '11123' => 'Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente.',
            '11121' => 'Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente. Intentá comparar los datos antes y durante la puesta en marcha de la estrategia más atentamente. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.',
            '11113' => 'Trabajaste de maneraeficiente e incorporaste nuevos hábitos. Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia.',
            '11111' => 'Es importante que profundices el análisis y observes cuidadosamente la situación de tu hogar. Encontraste dificultades para elaborar las estrategias. Seguí pensando qué otras ideas son posibles y orientadas hacia un consumo responsable. Registrar los datos es importante para implementarlas. Recordá realizarlo cuidadosamente. Es necesario que trabajes en la comparación de datos antes y durante la puesta en marcha de la estrategia. Seguí buscando formas eficientes de llevarlas a cabo para incorporar nuevos hábitos.'
        );
        if (isset($expressions[$no])) {
            return $expressions[$no];
        } else {
            return '';
        }
    }

    public static function fraceDataElectric($accesible, $data_collect, $avg_day_before, $avg_day_after, $diference_day) {
        $result = '';
        if (!$accesible) {
            $result = '';
        } else {
            if (!$data_collect) {
                $result = "Habiendo un medidor accesible, no tomaste los datos.";
            } else {
                $result = "Habiendo llevado a cabo el proyecto lograste comprobar que el consumo de tu hogar era de $avg_day_before Kwh antes de la estrategia y de $avg_day_after Kwh después de la estrategia. Como resultado se comprueba una variación del consumo de $diference_day Kwh.";
            }
        }
        return $result;
    }

    public static function fraceDataGas($accesible, $data_collect, $avg_day_before, $avg_day_after, $diference_day) {
        $result = '';
        if (!$accesible) {
            $result = '';
        } else {
            if (!$data_collect) {
                $result = "Habiendo un medidor accesible, no tomaste los datos.";
            } else {
                $result = "Habiendo llevado a cabo el proyecto lograste comprobar que el consumo de tu hogar era de $avg_day_before m3 antes de la estrategia y de $avg_day_after m3 después de la estrategia. Como resultado se comprueba una variación del consumo de $diference_day m3.";
            }
        }
        return $result;
    }

    public static function fraceDataAqua($accesible, $data_collect, $avg_day_before, $avg_day_after, $diference_day) {
        $result = '';
        if (!$accesible) {
            $result = '';
        } else {
            if (!$data_collect) {
                $result = "Habiendo un medidor accesible, no tomaste los datos.";
            } else {
                $result = "Habiendo llevado a cabo el proyecto lograste comprobar que el consumo de tu hogar era de $avg_day_before m3 antes de la estrategia y de $avg_day_after m3 después de la estrategia. Como resultado se comprueba una variación del consumo de  $diference_day m3.";
            }
        }
        return $result;
    }

    public static function fraceDataResidous($accesible, $data_collect, $avg_day_before, $avg_day_after, $diference_day) {
        $result = '';
        if (!$accesible) {
            $result = '';
        } else {
            if (!$data_collect) {
                $result = "No tomaste los datos.";
            } else {
                $result = "Habiendo llevado a cabo el proyecto lograste comprobar que la cantidad de residuos en tu hogar era de  $avg_day_before antes de la estrategia y de $avg_day_after después de la estrategia. Como resultado se comprueba una variación de $diference_day.";
            }
        }
        return $result;
    }

}

?>